#ifndef GENOS_DEFS_UARTDEFS_H
#define GENOS_DEFS_UARTDEFS_H

enum uart_stopbits_e
{
    UART_STOPBITS_ONE = 1,
	UART_STOPBITS_TWO = 2,
	UART_STOPBITS_HALF = 10,
	UART_STOPBITS_ONE_AND_HALF = 11
};

enum uart_parity_e
{
	ZILLOT_UART_PARITY_NONE = 'n',
	ZILLOT_UART_PARITY_EVEN = 'e',
	ZILLOT_UART_PARITY_ODD = 'o'
};

enum uart_flowcontrol_e
{
	UART_FLOWCONTROL_NONE = 0,
	UART_FLOWCONTROL_SOFTWARE,
	UART_FLOWCONTROL_HARDWARE
};

#endif
