# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:

- checkout: none

- script: curl.exe http://127.0.0.1:5000/wsl_library_updated?libname=igris
  displayName: 'Run test script through local flask server'
