docker:
  name: igris-testenv
  script: |
    FROM ubuntu:18.04
    RUN apt-get update && \
        apt-get install -y \
             sudo \
             python3 \
             python3-pip

    RUN apt-get install -y git
    RUN python3 -m pip install licant

pipeline:
  - name: igris
    watchdog: 600
    git:
      url: https://github.com/mirmik/igris
      name: igris
    steps:
      - name: make
        run: ./make.py

      - name: install
        run: ./make.py install

      - name: test
        run: ./runtests

      - name: licant-libs
        run: licant-libs .

    success_info: "Pipeline: {{pipeline_name}}\nCommit: {{commit_hash}}\nMessage: {{commit_message}}\n"
