name: Licant

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - { cc: gcc, cxx: g++ }
          - { cc: clang, cxx: clang++ }

    env:
      CC: ${{ matrix.compiler.cc }}
      CXX: ${{ matrix.compiler.cxx }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: mirmik/licant
          path: .ci/licant

      - name: Install licant
        run: python3 -m pip install ./.ci/licant

      - name: Build tests
        run: timeout 10m python3 ./make.py -j2 runtests

      - name: Test
        run: timeout 2m ./runtests
